Thang purge
uwindsorcss/css-discord-bot pull request #50
Opened 2022-04-06 03:44 UTC by phucthang1101

### What are you trying to accomplish?
Working on purge command and permission system.

### How are you accomplishing it?
I have added an array of important roles to check the user's permission before the command is executed.

### Is there anything reviewers should know?
I have done the same thing with "say" command and I think the "say" command is pretty much done. So check it out and review back to me.

- [x] Is it safe to rollback this change if anything goes wrong?
Yes

2022-04-12 00:51 UTC, kilbouri approved these changes

2022-04-16 16:46 UTC, prairir requested changes

2022-04-16 16:46 UTC, prairir commented on .gitignore
> +yarn.lock
I dont think we should gitignore `yarn.lock` the purpose of `yarn.lock` is so we always run the same package versions in production and in dev. That way we wouldnt get issues leftpad. `yarn.lock` has almost no issues unlike `gem.lock` which is all issues. 

Either way, i dont think we should have that there.

2022-04-16 16:46 UTC, prairir commented on src/index.ts
> +    const {command} = await import(filePath);
has loading in the commands been tested? I would expect there to be issues with the extension.

2022-04-16 16:46 UTC, prairir commented
very good work overall. Just had a few comments.

2022-04-17 19:13 UTC, merged